//
//  DateCalculator.m
//  Classes
//
//  Created by Derrick Park on 2021-02-23.
//


#import "DateCalculator.h"
// .m: implementation file
// categories
@interface DateCalculator()
// private properties (property = instance variable + getter + setter)
// private methods
@property (assign) float age;
- (BOOL) internalLogic: (float) age;

@end

@implementation DateCalculator {
  // private instance variables
  // _var (convention for instance variable in Obj-C)
  
  // generated by compiler when you use @property
  // NSString *_name;
  // float _age;
}

// -: instance method
// +: static(class) method
- (instancetype)initWithName:(NSString *) name AndAge:(float) age
{
  self = [super init];
  if (self) {
    _age = age;
    _name = name;
    // self.age = age; // [self setAge: age];
  }
  return self;
}

// generated by compiler when you use @property
//- (NSString *) name {
//  return _name;
//}
//
//- (void) setName:(NSString *) name {
//  _name = name;
//}

- (BOOL) canDateAPersonWithAge:(float) age
{
  return [self internalLogic: age];
}

- (BOOL) internalLogic: (float) age
{
  return (_age / 2 + 7) < age;
}

// toString in Java
- (NSString *)description
{
  return [NSString stringWithFormat:@"DateCalculator[name=%@, age=%.2f]", _name, _age];
}

@end
